package com.example.ui.components

import android.content.Context
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.Scope
import com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential
import com.google.api.client.http.javanet.NetHttpTransport
import com.google.api.client.json.gson.GsonFactory
import com.google.api.services.drive.Drive
import com.google.api.services.drive.DriveScopes
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.Collections

/**
 * Helper class to manage Google Sign-In and initialize the Google Drive API client
 * using configured OAuth client credentials.
 */
object GoogleDriveBackupHelper {

    private const val TAG = "GoogleDriveBackupHelper"

    /**
     * Custom OAuth Client ID override, if set programmatically.
     */
    var customOAuthClientId: String? = null

    /**
     * Resolves the OAuth Client ID from BuildConfig, string resources, or custom override.
     */
    fun getOAuthClientId(context: Context): String? {
        if (!customOAuthClientId.isNullOrBlank()) {
            return customOAuthClientId
        }

        // Try reading from BuildConfig generated by Secrets Gradle Plugin
        try {
            val buildConfigClass = Class.forName("${context.packageName}.BuildConfig")
            val field = buildConfigClass.getField("GOOGLE_OAUTH_CLIENT_ID")
            val clientId = field.get(null) as? String
            if (!clientId.isNullOrBlank() && !clientId.contains("YOUR_GOOGLE_OAUTH_CLIENT_ID")) {
                return clientId
            }
        } catch (e: Exception) {
            Log.d(TAG, "GOOGLE_OAUTH_CLIENT_ID not found in BuildConfig: ${e.message}")
        }

        // Try reading from strings.xml (e.g. default_web_client_id or server_client_id)
        val resNames = listOf("default_web_client_id", "server_client_id", "google_oauth_client_id")
        for (resName in resNames) {
            val resId = context.resources.getIdentifier(resName, "string", context.packageName)
            if (resId != 0) {
                val strValue = context.getString(resId)
                if (strValue.isNotBlank()) {
                    return strValue
                }
            }
        }

        return null
    }

    /**
     * Builds [GoogleSignInOptions] configured with email, profile, Drive scopes,
     * and optional OAuth Client ID token request.
     */
    fun getGoogleSignInOptions(
        context: Context,
        clientId: String? = getOAuthClientId(context)
    ): GoogleSignInOptions {
        val builder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()
            .requestScopes(Scope(DriveScopes.DRIVE_FILE))

        if (!clientId.isNullOrBlank() && !clientId.contains("YOUR_GOOGLE_OAUTH_CLIENT_ID")) {
            try {
                builder.requestIdToken(clientId)
            } catch (e: Exception) {
                Log.w(TAG, "Notice setting requestIdToken with client ID: ${e.message}")
            }
        }

        return builder.build()
    }

    /**
     * Initializes and returns a [GoogleSignInClient] using configured OAuth options.
     */
    fun getSignInClient(
        context: Context,
        clientId: String? = getOAuthClientId(context)
    ): GoogleSignInClient {
        val options = getGoogleSignInOptions(context, clientId)
        return GoogleSignIn.getClient(context, options)
    }

    /**
     * Retrieves the last signed-in Google account, if available.
     */
    fun getLastSignedInAccount(context: Context): GoogleSignInAccount? {
        return GoogleSignIn.getLastSignedInAccount(context)
    }

    /**
     * Saves connected account information to SharedPreferences for persistent authentication.
     */
    fun saveConnectedAccount(context: Context, name: String?, email: String?, photoUrl: String? = null, provider: String = "Google") {
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        val currentName = prefs.getString("account_name", "") ?: ""
        val currentEmail = prefs.getString("account_email", "") ?: ""
        val currentPhoto = prefs.getString("account_photo_url", "") ?: ""
        val currentProvider = prefs.getString("account_provider", "Google") ?: "Google"

        val finalName = if (!name.isNullOrBlank()) name else currentName
        val finalEmail = if (!email.isNullOrBlank()) email else currentEmail
        val finalPhoto = if (!photoUrl.isNullOrBlank()) photoUrl else currentPhoto
        val finalProvider = if (!provider.isNullOrBlank()) provider else currentProvider

        prefs.edit()
            .putString("account_name", finalName)
            .putString("account_email", finalEmail)
            .putString("account_photo_url", finalPhoto)
            .putString("account_provider", finalProvider)
            .putBoolean("is_signed_in", true)
            .apply()
    }

    /**
     * Gets the saved account provider ("Google", "Microsoft", or "LinkedIn").
     */
    fun getSavedAccountProvider(context: Context): String {
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        return prefs.getString("account_provider", "Google") ?: "Google"
    }

    /**
     * Gets the saved account email from preferences.
     */
    fun getSavedAccountEmail(context: Context): String {
        val account = getLastSignedInAccount(context)
        if (!account?.email.isNullOrBlank()) return account!!.email!!
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        return prefs.getString("account_email", "") ?: ""
    }

    /**
     * Gets the saved account name from preferences.
     */
    fun getSavedAccountName(context: Context): String {
        val account = getLastSignedInAccount(context)
        if (!account?.displayName.isNullOrBlank()) return account!!.displayName!!
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        val saved = prefs.getString("account_name", "") ?: ""
        return if (saved.isNotBlank()) saved else if (isSignedIn(context)) "Google Account" else "Guest User"
    }

    /**
     * Gets the saved account photo URL from preferences or active account.
     */
    fun getSavedPhotoUrl(context: Context): String {
        val account = getLastSignedInAccount(context)
        if (account?.photoUrl != null && account.photoUrl.toString().isNotBlank()) {
            return account.photoUrl.toString()
        }
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        return prefs.getString("account_photo_url", "") ?: ""
    }

    /**
     * Checks if the user is currently signed into a Google Account.
     */
    fun isSignedIn(context: Context): Boolean {
        if (getLastSignedInAccount(context) != null) return true
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        return prefs.getBoolean("is_signed_in", false)
    }

    /**
     * Clears local persisted account state on sign out.
     */
    fun clearSavedAccount(context: Context) {
        val prefs = context.getSharedPreferences("google_drive_backup_prefs", Context.MODE_PRIVATE)
        prefs.edit()
            .remove("account_name")
            .remove("account_email")
            .remove("account_photo_url")
            .remove("account_provider")
            .putBoolean("is_signed_in", false)
            .apply()
    }

    /**
     * Data class holding actual Google Drive / Account storage quota usage.
     */
    data class DriveStorageQuota(
        val usageBytes: Long,
        val limitBytes: Long,
        val usageInDriveBytes: Long = 0L,
        val usageInDriveTrashBytes: Long = 0L,
        val isFetched: Boolean = false
    ) {
        val usagePercentage: Float
            get() = if (limitBytes > 0L) (usageBytes.toFloat() / limitBytes.toFloat()).coerceIn(0f, 1f) else 0f

        val formattedUsage: String
            get() = formatBytes(usageBytes)

        val formattedLimit: String
            get() = if (limitBytes > 0L) formatBytes(limitBytes) else "15.0 GB"

        private fun formatBytes(bytes: Long): String {
            return when {
                bytes <= 0L -> "0 B"
                bytes < 1024L -> "$bytes B"
                bytes < 1024L * 1024L -> String.format(java.util.Locale.US, "%.1f KB", bytes / 1024f)
                bytes < 1024L * 1024L * 1024L -> String.format(java.util.Locale.US, "%.1f MB", bytes / (1024f * 1024f))
                else -> String.format(java.util.Locale.US, "%.1f GB", bytes / (1024f * 1024f * 1024f))
            }
        }
    }

    /**
     * Fetches real-time Google Drive storage quota info.
     */
    suspend fun fetchDriveStorageQuota(context: Context): DriveStorageQuota? {
        return withContext(Dispatchers.IO) {
            val drive = getDriveService(context) ?: return@withContext null
            try {
                val about = drive.about().get().setFields("storageQuota, user").execute()
                val quota = about.storageQuota
                if (quota != null) {
                    val usage = quota.usage ?: 0L
                    val limit = quota.limit ?: (15L * 1024L * 1024L * 1024L)
                    val inDrive = quota.usageInDrive ?: 0L
                    val inTrash = quota.usageInDriveTrash ?: 0L
                    DriveStorageQuota(
                        usageBytes = usage,
                        limitBytes = limit,
                        usageInDriveBytes = inDrive,
                        usageInDriveTrashBytes = inTrash,
                        isFetched = true
                    )
                } else null
            } catch (e: Exception) {
                Log.w(TAG, "Notice fetching real-time Drive quota: ${e.message}")
                null
            }
        }
    }

    /**
     * Checks real-time network connectivity and latency to Google services.
     */
    suspend fun checkConnectionHealth(context: Context): Pair<String, Long> {
        return withContext(Dispatchers.IO) {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? android.net.ConnectivityManager
            val activeNetwork = cm?.activeNetwork
            val caps = cm?.getNetworkCapabilities(activeNetwork)
            val isConnected = caps?.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_INTERNET) == true

            if (!isConnected) {
                return@withContext Pair("Offline", -1L)
            }

            val startTime = System.currentTimeMillis()
            var reachable = false
            try {
                val url = java.net.URL("https://www.google.com/generate_204")
                val connection = (url.openConnection() as java.net.HttpURLConnection).apply {
                    connectTimeout = 3000
                    readTimeout = 3000
                    requestMethod = "GET"
                }
                val code = connection.responseCode
                reachable = (code == 204 || code == 200)
                connection.disconnect()
            } catch (_: Exception) {
                reachable = false
            }

            val latency = (System.currentTimeMillis() - startTime).coerceAtLeast(1L)
            if (reachable) {
                val healthStatus = when {
                    latency < 100 -> "Excellent"
                    latency < 300 -> "Good"
                    else -> "Fair"
                }
                Pair(healthStatus, latency)
            } else {
                Pair("Limited", latency)
            }
        }
    }

    /**
     * Checks if the active Google account has been granted Google Drive file permissions.
     */
    fun hasDrivePermission(context: Context): Boolean {
        val account = getLastSignedInAccount(context) ?: return false
        return GoogleSignIn.hasPermissions(account, Scope(DriveScopes.DRIVE_FILE))
    }

    /**
     * Initializes the [Drive] API client using GoogleAccountCredential and current Google account.
     */
    suspend fun getDriveService(
        context: Context,
        account: GoogleSignInAccount? = getLastSignedInAccount(context)
    ): Drive? {
        return withContext(Dispatchers.IO) {
            val activeAccount = account ?: getLastSignedInAccount(context) ?: return@withContext null
            try {
                val credential = GoogleAccountCredential.usingOAuth2(
                    context,
                    Collections.singletonList(DriveScopes.DRIVE_FILE)
                )
                credential.selectedAccount = activeAccount.account

                Drive.Builder(
                    NetHttpTransport(),
                    GsonFactory.getDefaultInstance(),
                    credential
                )
                    .setApplicationName("Lipi")
                    .build()
            } catch (e: Exception) {
                Log.e(TAG, "Failed to initialize Google Drive API client", e)
                null
            }
        }
    }

    /**
     * Signs out the user from Google Sign-In cleanly.
     */
    fun signOut(context: Context, onComplete: (() -> Unit)? = null) {
        clearSavedAccount(context)
        try {
            val client = getSignInClient(context)
            client.signOut().addOnCompleteListener {
                onComplete?.invoke()
            }
        } catch (e: Exception) {
            onComplete?.invoke()
        }
    }
}
