package com.example.ui.components

import android.content.Context
import android.util.Log
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.Scope
import com.google.api.client.googleapis.extensions.android.gms.auth.GoogleAccountCredential
import com.google.api.client.http.javanet.NetHttpTransport
import com.google.api.client.json.gson.GsonFactory
import com.google.api.services.drive.Drive
import com.google.api.services.drive.DriveScopes
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.Collections

/**
 * Helper class to manage Google Sign-In and initialize the Google Drive API client
 * using configured OAuth client credentials.
 */
object GoogleDriveBackupHelper {

    private const val TAG = "GoogleDriveBackupHelper"

    /**
     * Custom OAuth Client ID override, if set programmatically.
     */
    var customOAuthClientId: String? = null

    /**
     * Resolves the OAuth Client ID from BuildConfig, string resources, or custom override.
     */
    fun getOAuthClientId(context: Context): String? {
        if (!customOAuthClientId.isNullOrBlank()) {
            return customOAuthClientId
        }

        // Try reading from BuildConfig generated by Secrets Gradle Plugin
        try {
            val buildConfigClass = Class.forName("${context.packageName}.BuildConfig")
            val field = buildConfigClass.getField("GOOGLE_OAUTH_CLIENT_ID")
            val clientId = field.get(null) as? String
            if (!clientId.isNullOrBlank() && !clientId.contains("YOUR_GOOGLE_OAUTH_CLIENT_ID")) {
                return clientId
            }
        } catch (e: Exception) {
            Log.d(TAG, "GOOGLE_OAUTH_CLIENT_ID not found in BuildConfig: ${e.message}")
        }

        // Try reading from strings.xml (e.g. default_web_client_id or server_client_id)
        val resNames = listOf("default_web_client_id", "server_client_id", "google_oauth_client_id")
        for (resName in resNames) {
            val resId = context.resources.getIdentifier(resName, "string", context.packageName)
            if (resId != 0) {
                val strValue = context.getString(resId)
                if (strValue.isNotBlank()) {
                    return strValue
                }
            }
        }

        return null
    }

    /**
     * Builds [GoogleSignInOptions] configured with email, profile, Drive scopes,
     * and optional OAuth Client ID token request.
     */
    fun getGoogleSignInOptions(
        context: Context,
        clientId: String? = getOAuthClientId(context)
    ): GoogleSignInOptions {
        val builder = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestEmail()
            .requestProfile()
            .requestScopes(Scope(DriveScopes.DRIVE_FILE))

        if (!clientId.isNullOrBlank() && !clientId.contains("YOUR_GOOGLE_OAUTH_CLIENT_ID")) {
            try {
                builder.requestIdToken(clientId)
            } catch (e: Exception) {
                Log.w(TAG, "Failed to set requestIdToken with client ID: ${e.message}")
            }
        }

        return builder.build()
    }

    /**
     * Initializes and returns a [GoogleSignInClient] using configured OAuth options.
     */
    fun getSignInClient(
        context: Context,
        clientId: String? = getOAuthClientId(context)
    ): GoogleSignInClient {
        val options = getGoogleSignInOptions(context, clientId)
        return GoogleSignIn.getClient(context, options)
    }

    /**
     * Retrieves the last signed-in Google account, if available.
     */
    fun getLastSignedInAccount(context: Context): GoogleSignInAccount? {
        return GoogleSignIn.getLastSignedInAccount(context)
    }

    /**
     * Checks if the user is currently signed into a Google Account.
     */
    fun isSignedIn(context: Context): Boolean {
        return getLastSignedInAccount(context) != null
    }

    /**
     * Checks if the active Google account has been granted Google Drive file permissions.
     */
    fun hasDrivePermission(context: Context): Boolean {
        val account = getLastSignedInAccount(context) ?: return false
        return GoogleSignIn.hasPermissions(account, Scope(DriveScopes.DRIVE_FILE))
    }

    /**
     * Initializes the [Drive] API client using GoogleAccountCredential and current Google account.
     */
    suspend fun getDriveService(
        context: Context,
        account: GoogleSignInAccount? = getLastSignedInAccount(context)
    ): Drive? {
        return withContext(Dispatchers.IO) {
            val activeAccount = account ?: getLastSignedInAccount(context) ?: return@withContext null
            try {
                val credential = GoogleAccountCredential.usingOAuth2(
                    context,
                    Collections.singletonList(DriveScopes.DRIVE_FILE)
                )
                credential.selectedAccount = activeAccount.account

                Drive.Builder(
                    NetHttpTransport(),
                    GsonFactory.getDefaultInstance(),
                    credential
                )
                    .setApplicationName("Lipi")
                    .build()
            } catch (e: Exception) {
                Log.e(TAG, "Failed to initialize Google Drive API client", e)
                null
            }
        }
    }

    /**
     * Signs out the user from Google Sign-In cleanly.
     */
    fun signOut(context: Context, onComplete: (() -> Unit)? = null) {
        val client = getSignInClient(context)
        client.signOut().addOnCompleteListener {
            onComplete?.invoke()
        }
    }
}
